// <auto-generated />
using CachedRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CachedRepository.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20180926231812_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("CachedRepository.Data.Models.VehicleManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("CachedRepository.Data.Models.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("VehicleManufacturerId");

                    b.HasKey("Id");

                    b.HasIndex("VehicleManufacturerId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("CachedRepository.Data.Models.VehicleModel", b =>
                {
                    b.HasOne("CachedRepository.Data.Models.VehicleManufacturer", "VehicleManufacturer")
                        .WithMany("Models")
                        .HasForeignKey("VehicleManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
